### ISSUE TITLE
Strange R^2 value

### ISSUE THREAD

**Issue by Luosanj** [theislab/ncem_tutorials#2]
Hi, 
May I ask why the R^2(r-squared) value so small, even negative values existed? This is absolutely strange. 

![image](https://user-images.githubusercontent.com/46926952/183798969-135ed5bd-cfc3-4531-9481-711c8201734f.png)

**Comment by AnnaChristina** [comment]
Hi @Luosanj,

please be aware that we only show the training here for 5 epochs. So this model has not converged yet. We usually would train for 1000 epochs and assess convergence during training, so the small $R^2$. value is reasonable. 

Please be also aware that the coefficient of determination $R^2$ can in fact be negative as 

$$R^2 = 1 - \frac{\sum_i e_i^2}{\sum_i (y_i-\hat{y})^2}$$ for residuals $e_i$ and $\hat{y}$ mean of $y_i$.

For an converged model, the values will increase, but this is not expected after only 5 epochs. Hope this answers your question. We additionally report the pearson correlation coefficient `r_squared_linreg` which is in fact non negative but reports a slightly different view on the model performance.

**Comment by Luosanj** [comment]
@AnnaChristina  Thanks a lot for your answer ! I am clear now.

**Comment by Luosanj** [comment]
Hi @AnnaChristina,
     If I want to see the final convergence r-square, how to operate it ?
     I have tried several times to set 'epochs = 1000' and run. Yet, the output just shows results of top 30-50  epochs randomly. How to deal with this issue?
     Thanks !


![image](https://user-images.githubusercontent.com/46926952/183909504-e5494a04-75b5-4bb0-9f92-00f6aea4879c.png)

**Comment by AnnaChristina** [comment]
This part of ncem is not designed to be run in a jupyter notebook, we just placed it here in order to show an example how you would pass custom deconvoluted data. If you are interested in running more extensive ncem experiments, you may want to check out how to submit train scripts on your compute cluster. Examples for train scripts are provided here: https://github.com/theislab/ncem_benchmarks/tree/main/scripts

Those scripts will save pickle files with training histories and evaluations on train, test and evaluation set within a specified folder, which can be loaded after training.
